TRUNCATE TABLE tags RESTART IDENTITY CASCADE;
TRUNCATE TABLE gift_certificates RESTART IDENTITY CASCADE;
TRUNCATE TABLE orders RESTART IDENTITY CASCADE;
TRUNCATE TABLE gift_certificates_tags RESTART IDENTITY CASCADE;
