spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecl
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: false